name: Releases

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: mkdir BestDealHelper-${RELEASE_VERSION}
      - run: cp -v info.txt main.js chroma.min.js BestDealHelper-${RELEASE_VERSION}/
      - run: zip -r BestDealHelper-${RELEASE_VERSION}.zip BestDealHelper-${RELEASE_VERSION}
      - uses: ncipollo/release-action@v1
        with:
          name: Release ${{ env.RELEASE_VERSION }}
          bodyFile: "RELEASE.md"
          artifacts: BestDealHelper-${{ env.RELEASE_VERSION }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}